services:
  - type: web
    name: iai-test-ui
    runtime: node
    plan: free
    buildCommand: npm install --prefix server && npm install --prefix client && npm --prefix client run build
    startCommand: bash server/scripts/startup.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PW_FRAMEWORK_PATH
        value: /opt/render/project/playwright-automation-framework
      - key: PW_AUTO_GITHUB_TOKEN
        sync: false
      - key: PW_AUTO_JWT_SECRET
        sync: false
      - key: TURSO_DB_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
